#!/bin/bash
read -p "let your thoughts die here:: " input

echo "$input" >> ~/.3emac.rt
#disable backup
#echo "$input" >> ~/.3emac.rtbackup
#clear entire file
#echo "" > ~/.3emac.rt
#clear prompt and then add neofetch because it makes it look cool
clear
neofetch
